### ISSUE TITLE
Replace pseudoinverse

### ISSUE THREAD

**Issue by PaulWAyers** [theochem/gopt#3]
The current pseudoinverse (hard-coded) doesn't always converge because numpy uses an iterative(!) algorithm for SVD instead of a true factorization. The best solution I think is to default to the least-squares generalized inverse and allow users to use the SVD-based inverse if and only if they wish to. This also lets us eliminate the home-build pseudoinverse from the math library for `Gopt`.

This is what was done in the `Procrustes` package.
https://github.com/theochem/procrustes/blob/ad70b01578152d4f3c7570c065c7e2b1e8ac553b/procrustes/generic.py#L88

@tczorro do you want to take a crack at this, or do you want me to do it?

**Comment by tczorro** [comment]
@PaulWAyers  Got a little busy this week. But I will take some this time weekend to check the SVD-based inverse function in GOpt. Will let you know the progress
